version: 2

before:
  hooks:
    - go mod tidy 

builds:
  - id: michi
    main: ./cmd/michi.go
    binary: michi
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: default
    formats: ['tar.gz']
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md


release:
  github:
    owner: michiapp 
    name: michi     
  disable: false 
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
