version: 2

before:
  hooks:
    - go mod tidy 

builds:
  - id: michi
    main: ./cmd/michi.go
    binary: michi
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64 
    ldflags:
      - -s -w

archives:
  - id: default
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

release:
  disable: false 
  github:
    owner: michiapp
    name: michi
  footer: |
    ---
    🔎 michi — a blazing-fast local search multiplexer.  
    👉 Install instructions in the README.  
    ❤️ Contributions, feedback, and stars are welcome!
